### PR TITLE
Use jbuilder and result + seq compatibility packages

### PR DESCRIPTION
**Pull request by hcarty**
This is a somewhat invasive PR with hopefully understandable per-commit changes.

Summary:
* e95ded8 uses jbuilder as the build system, moving the cppo calls to the `-V` flag to automatically parse the OCaml version.  This also removes support for cpp as a preprocessor.
* f98bd91 removes an unexposed value caught by jbuilder's `--dev` warnings
* 79a49f6 adds a new `Makefile` for convenience, including a `make repl` target which starts a custom utop session with `Stdcompat` already loaded
* e0a3f20 updates the opam metadata to match the jbuilder port
* 7cb6bc6 Uses the `result` and `seq` compatibility packages to make `stdcompat` compatible with other libraries using the matching types on compiler versions which don't have them natively

### CODE REVIEW

**Review by thierry-martinez — APPROVED** [review]
Cherry-picked! This value was there due to a wrong use of copy-paste!

**Review by thierry-martinez — COMMENTED** [review]
The change has been pushed to master in https://github.com/thierry-martinez/stdcompat/commit/92b7bc6d5bce9e7940b15638e71259776643eb8f .

Compared to what is proposed in this commit, the result and seq packages are not required but are used if available.

**Review by thierry-martinez — COMMENTED** [review]
The commit https://github.com/thierry-martinez/stdcompat/commit/6fa3c3536581fac825e790a1e8dbbd41749eef1b uses `cppo`'s `-V` flag with the `OCAML_VERSION` variable: the tuple allows a more convenient lexicographic comparison, and I obtained compatibility with `cpp` with some `sed` hacks.

**Comment by hcarty** [comment]
Thank you for working on adapting this to fit the project's needs! I'm away from a computer for the day but if there's anything left to do when I'm back I'd be happy to help out.

**Comment by thierry-martinez** [comment]
I merged the jbuild script. I plan to keep the Makefile as-is to allow stdcompat to be built without jbuilder. Do you see something more to do or shall I close the pull request?

**Comment by hcarty** [comment]
I think this is good.  Thank you very much!

**Comment by hcarty** [comment]
It would be nice to have a release to opam with these changes in place so that users can take advantage of the type compatibility.  It's possible to pin to `master` for now though.

**Comment by thierry-martinez** [comment]
Released to opam: https://github.com/ocaml/opam-repository/pull/11858 . Thanks for merging!

**Comment by hcarty** [comment]
You're welcome - thanks for getting that out so quickly!

**Pull request closed without merging**
